# This file contains params for the simulations
simParams:
        timeStep: 0.002
        stepsPerControlLoop: 50
        numSolverIterations: 300
        gravity: -10
        contactBreakingThreshold: 0.0001
        contactSlop: 0.0001
        moveThreshold: 0.1
        maxStopMoveLength: 25
terrainMapParams:
        mapWidth: 300 # width of matrix
        mapHeight: 300 # height of matrix
        widthScale: 0.1 # each pixel corresponds to this distance
        heightScale: 0.1
senseParams:
        senseDim: [2,2] # width (meter or angle) and height (meter or angle) of terrain map or point cloud
        senseResolution: [64,64] # array giving resolution of map output (num pixels wide x num pixels high)
        senseType: -1 # 0 for terrainMap, 1 for lidar depth image, 2 for lidar point cloud
        sensorPose: [[0,0,0],[0,0,0,1]] # pose of sensor relative to body
robotParams: # dynamical parameters of clifford robot
        maxThrottle: 20
        maxSteerAngle: 0.5
        susOffset: -0.00
        susLowerLimit: -0.01
        susUpperLimit: 0.00
        susDamping: 10
        susSpring: 500
        traction: 1.25
        masScale: 1.0
dataCollectParams:
        numParallelSims: 4
        trajectoryLength: 64
        totalNumTrajectories: 1200
