# This file contains terrain parameters used to collect training data
terrainParams:
        AverageAreaPerCell: 0.5
        cellPerlinScale: 0.5
        cellHeightScale: 0.6
        smoothing: 0.7
        perlinScale: 1.0
        perlinHeightScale: 0.2
        flatRadius: [0.5,0.5]
        blendRadius: 0.5
